services:
  db:
    image: postgres:15
    container_name: workorder_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - workorder-network

  backend:
    build:
      context: ./backend-work-order
      dockerfile: Dockerfile
    container_name: workorder_backend
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
      PORT: 3000
    depends_on:
      - db
    networks:
      - workorder-network

  frontend:
    build:
      context: ./frontend-work-order
      dockerfile: Dockerfile
    container_name: workorder_frontend
    restart: always
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3000"
    depends_on:
      - backend
    networks:
      - workorder-network

volumes:
  postgres_data:

networks:
  workorder-network:
    driver: bridge
